[package]
name = "dwarf-napi"
version.workspace = true
edition.workspace = true
description = "Node.js bindings for dwarf"
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
dwarf-core.workspace = true
dwarf.workspace = true
anyhow.workspace = true
clap.workspace = true
napi = { version = "3", features = ["tokio_rt"] }
napi-derive = "3"
tokio.workspace = true

[build-dependencies]
napi-build = "2"

[features]
default = ["component-model-async"]
opt-size = [
    "dwarf-core/opt-size",
    "dwarf/opt-size"
]
component-model-async = [
    "dwarf-core/component-model-async",
    "dwarf/component-model-async",
]
